### ISSUE TITLE
 Have a Restart Party once a month 

### ISSUE THREAD

**Issue by ka81** [Liverpool-UK/somebody-should#18]
Hi All, 

Was thinking about code for liverpool and one of the things we could do is help people repair there electronics and reduce waste . I know restart London is trying to help people expand the idea across the UK and have a pack ready.
Any help with it would be good.

Caroline

**Comment by amcewen** [comment]
Nice idea.  Obv. @DoESLiverpool is available for holding it if that makes sense.

There's more info on the Restart Project (in case any hasn't come across them before) at https://therestartproject.org/

**Comment by jamieisboss** [comment]
I hadn't heard of this before but I'd definitely like to do it, fixing stuff is as good as making stuff for me and it seems like a good way of supporting people without handouts and mabe a positive message to help with de-demonising the 'on benefits with a 32" tv' thing i still hear from time to time which annoys the hell out of me because that's the standard cheap tv size an everyone should be able to go to a library, borrow game of thrones on dvd, binge it, go back and get the books, binge them then cry waiting 9 years for the next book.

As for where, ground level seems like a good idea (much as i love DoES) partly because of the psychology of 'just wandering past with this broken radio and saw the sign', partly because you don't know how big or heavy a thing someone might want to bring and while you're on the 4th floor it might well restrict some people, even with the lifts. 

**I've read more of the pack now**
I really like that they're run in pubs and places where people would go anyway and our extra special sauce could be having DoES as a regular party that dealt with harder stuff (and possibly people from the DoES community who might volunteer would get more out of the challenge of fixing the more complex stuff?)

I think a good balance could be roaming it around a bit into communities then having a central one at DoES where there's a lot more kit. I think we'd get more good done in a community centre or a big back room in a pub in toxteth or Everton, especially if we could 'wait list' stuff too complex for a take around fixin' kit until a DoES party.(and maybe even know that a laser cut or 3d printed part could be fabbed before the party so even more things could be fixed) 

**Kit**
I think I own at least one of everything you need plus a bunch more stuff. Only thing I don't have is a PAT tester; ~~I don't know what @DoESsean would say, (i can make an educated guess at it being something sensible about having to not spend all the money without making more)  but maybe Solve could buy one of them. Basically if I can sell a company PAT testing for them to make the tester into an investment, then we could use it for community stuff like this without charging . Unless DoES already has one? Or is looking for someone to do some PAT testing?~~ Im Watching some 2nd hand ones on ebay, if the price doesn't get sniped they're not too bad. Maybe the Uni would donate an older one as an idea too, they probably have to refresh them in some cycle anyway and with all that new development this is more likely to be the time as nothing new needs testing for 3 years so testing current kit with new testers makes a kind of sense if someone else thought like that. I'll look into it and if not I'll see if there's anyone who owes me a favour.

**Backing it**
Either way, from a Business Development person head, this is the type of thing Solve want to put our name to, i'll ask @DoESsean (who should really have a handle on here that isnt DoES related) how far our current insurance would go towards covering these events; we are insured to run training events at any remote location worldwide, so we might have enough cover because of that, or maybe only have to tack on a little more for electronics fixing courses at any location. We'd be happy to do the marketing and location recon too, I think Sean could probably name every Pub that would make a good venue between Glasgow and Brighton from his ITBox escapades so, see what he says when he chips in i guess. 

**Question**
I've tried to find this before and not but does anyone know of a short course that doesn't cost the earth that means you are officially certified knowledgeable and safe to open things that run on mains voltage and do this type of thing? I imagine that might be an issue for the insurance, though that's what liability waivers are for i suppose. 

I'd actually quite like someone who knows to tell me i am actually doing things right though; and would pay for that personally if it's a thing that exists that i can afford, lord knows I've fixed enough stuff, it'd be good to know I wasn't risking life and limb every time. If it does and is around that price for the 4 people it suggests to get started, maybe awesome foundation grant? I'll do an ignite talk about tech and community as recompense.

**Comment by amcewen** [comment]
For getting out into the wider Liverpool it might be worth chatting to Denise at the library - I'm sure she'd be up for helping host them there.  Toxteth library, for example, has an event space.  Probably worth posting something to the DoES google group if you want to drum up more volunteers to help run things.

**Comment by jamieisboss** [comment]
I'll have a chat with Sean when he gets back, we'd need to vote before i can say we're doing this but I can't see him saying no, probably just a formality but he might know something I dont that we'd have to work around first. Can't see that happening but i remembered my director obligations. Once that's sorted that sounds like a great place to start, 

@ka81 I'm steamrolling a bit here, so I'll stop and cut you back in. I was actually trying to suggest we do the bits a company could help with from the pack  but i got excited and that didnt come across. 

It was your idea, you were asking for people to help, so it's your project unless you say otherwise, we'll back you all the way.

**Comment by ka81** [comment]
I'm all for anyone rolling with it ...currently snowed under so that's
helpful.

Its a great idea but i don't own it ...lol.. so if you want to lead with it
Jamie run with it ... I'll help out when i get chance x x

Caroline

**Comment by jamieisboss** [comment]
Cool, as long as im not taking anyones fun.

edit: sorry, fixed it

**Comment by jamieisboss** [comment]
@DoESsean Whats Our insurance situ re: the above?

**Comment by jamieisboss** [comment]
Started [a repo,](https://github.com/Liverpool-UK/Restart-Parties) already this thread we've outgrown

**Comment by hswifthunt** [comment]
Hello! Reviving this very old thread, because I'm looking to organise a couple Restart Parties in Liverpool soon-ish. My pal Tenyen is a volunteer at a lot of the London events, and said he'd try to come up to help kick off this one (good to have someone with experience pitching in at first!). I'd like to do it either at The Bluecoat or at the Granby Street Market, or both, and am currently inquiring about all that. Should be relatively straightforward. 

Anyone around who would be up for volunteering as a fixer? Let me know so I can try to get a date that works for everyone.

**Comment by amcewen** [comment]
Cool!  Probably worth hooking up with @huffeec, as I know he's been looking at this sort of thing, and also worth pinging George from Transition Towns Liverpool as there's been talk of them arranging something like this too (but no-one has, to my knowledge, pulled it off yet).

The [DoES Google group](https://doesliverpool.com/get-involved/) would also be a good place to solicit for fixers.

(If the venues fall through, I'm sure we could host it at DoES Liverpool)

**Comment by hswifthunt** [comment]
Thanks, Adrian! I’ll check in on the list next, just wanted to start here since it came up when I searched for Restart Liverpool and didn’t want to duplicate anything. Thanks for the tips!!

**Comment by huffeec** [comment]
It would be worth having a chat with George at http://www.transitionliverpool.org/

It's something we'd like to do at DoES but it's one of the ideas that's fallen into the 'after we move' list, but happy to chat about it if that's useful. I'm sure there would be people in the DoES community who'd be interested in getting involved.

**Comment by amcewen** [comment]
So, when I was at the Festival of Maintenance last week there was a talk from Janet Gunter of the Restart Project.  She pointed out that the 20th October will be this year's [International Repair Day](https://ifixit.org/blog/9384/international-day-of-repair/)

That's not too far off, if anyone wanted to organise something at @DoESLiverpool... (given I was suggesting that to @sean-anotherone and @sjcolosimo earlier this evening)

**Comment by DoESsean** [comment]
If someone tells me that they are willing to be here and facilitate, I'll
push something out to the Google Group, Facebook, etc. If not, I'll keep
schtum :)

**Comment by sjcolosimo** [comment]
I could be there that day to help! I also have something that needs fixing so it would be worthwhile.

**Comment by sjcolosimo** [comment]
> I could be there that day to help! I also have something that needs fixing so it would be worthwhile.

Besides, you know, for the greater good etc.

**Comment by amcewen** [comment]
This has been rather long-running, but there is now a date for the first Repair Cafe - 29th September 2019, at [DoES Liverpool](https://doesliverpool.com) (as part of the [Festival of Maintenance](https://festivalofmaintenance.org.uk/), also worth a look).  More details being [discussed on the DoES Liverpool Google Group](https://groups.google.com/forum/#!topic/does-liverpool/HbR3RBPrUBU)

**Comment by amcewen** [comment]
The Repair Cafe's have become a monthly fixture - tickets for the latest available at https://www.eventbrite.co.uk/e/repair-cafe-at-does-liverpool-february-2022-tickets-268825794187 so I think we can close this!  :grinning:
