### ISSUE TITLE
Junction of Hanover Street and Gradwell Street is confusing

### ISSUE THREAD

**Issue by johnmckerrell** [Liverpool-UK/somebody-should#4]
The junction of Hanover Street and Gradwell Street is confusing for motorists and pedestrians alike. A (mini) roundabout at this point seems like it would make most sense as it would hopefully force people to make more explicit decisions.

http://www.openstreetmap.org/?mlat=53.40324&mlon=-2.98414#map=18/53.40324/-2.98414

**Comment by amcewen** [comment]
I had a chat with someone at the council about this recently, as he'd seen the list and wondered if it was something that could easily be fixed.

Turns out it'd cost ~£150k to fix, which I think makes it probably a "won't fix" issue.  At least until someone is doing some other work on that junction?

Is there an easy way to encode lat/lon into a label, without spawning a billion labels as things get reported?  I'm just wondering if there's a way to capture where this problem was reported so someone in the future could query the issue list and find all the things for an area?  Would a "geo" label, plus a comment containing some GeoJSON or something work...?

**Comment by johnmckerrell** [comment]
Found GEO:53.40324;-2.98414 on http://microformats.org/wiki/geo which might do, I don't appear to be able to add labels to this issue though.

**Comment by amcewen** [comment]
I think, now you're a member of the "organisation" that you should be able to add labels, etc.  Let me know if you can't, and I'll fiddle with the settings some more.

**Comment by johnmckerrell** [comment]
![IMG_9430](https://user-images.githubusercontent.com/27243/126545813-1ad31df1-cc7d-4370-99f5-5b3134119958.jpg)

I've not been down this end in a while but I'm glad to notice a change has been made, but obviously whoever found this issue and resolved it didn't agree with me that a roundabout would be a better option as they've simply made Hanover Street the through road.
